generateOres = true
blacklistedOres = []
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = false
disableItemTagTooltips = false
newVersionMessage = false
colorWaterLava = true
enableDebugCommands = false
